FROM php:7.4-apache

WORKDIR /var/www/html
RUN docker-php-ext-install mysqli
COPY backend/php.ini /usr/local/etc/php/conf.d/application.ini

COPY backend/index.php backend/conexao.php ./
COPY frontend/index.html ./frontend.html
COPY frontend/css.css frontend/js.js ./

EXPOSE 80
